name: Build and Deploy
on:
  push:
    branches:
      - CD-config
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 'latest'
