name: Deploy
on:
  push:
    branches:
      - CD-config
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Run npm Install
        run: |
          npm i -g corepack
          npm install

      - name: build
        run: |
          npx expo export -p web
          gh-pages -t -d dist
